title: James Dalton's Random Musings
email: blog@james-dalton.net
author: James Dalton
description: >- 
  Things I've learned about software engineering and math.

show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

google_analytics: UA-121857845-1

  # generate social links in footer
  social_links:
    twitter: JamesDDalton
    github:  jamesdalton
    rss: rss
    linkedin: james-dalton-0a71041a
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# jekyll-seo-tag
social:
  name: James Dalton
  links:
    - https://twitter.com/JamesDDalton
    - https://linkedin.com/in/james-dalton-0a71041a
    - https://github.com/jamesdalton
twitter:
  username: JamesDDalton
  card: summary

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap


exclude:
  - README.md
  - scripts
  - Gemfile
  - Gemfile.lock
